### ISSUE TITLE
It's a trap. Error.

### ISSUE THREAD

**Issue by tomjrob** [HealthHackAu2016/cbr-improved-citations#1]
Hey peeps, trying to use this today and I get the following on a bibtex library exported from Mendeley.

`Traceback (most recent call last):
  File "/Users/tomjrob/.virtualenvs/citex/bin/citex", line 11, in <module>
    sys.exit(console())
  File "/Users/tomjrob/.virtualenvs/citex/lib/python2.7/site-packages/dedupe.py", line 84, in console
    main(args.files, args.output_dir)
  File "/Users/tomjrob/.virtualenvs/citex/lib/python2.7/site-packages/dedupe.py", line 34, in main
    in_ = list(btx_io.read_bib_entries(*filenames))
  File "/Users/tomjrob/.virtualenvs/citex/lib/python2.7/site-packages/btx_io.py", line 23, in read_bib_entries
    loc.replace('}.' ,'},'), 'bibtex').entries.values():
  File "/Users/tomjrob/.virtualenvs/citex/lib/python2.7/site-packages/pybtex/database/__init__.py", line 866, in parse_string
    return parser.parse_string(value)
  File "/Users/tomjrob/.virtualenvs/citex/lib/python2.7/site-packages/pybtex/database/input/bibtex.py", line 372, in parse_string
    for entry in entry_iterator:
  File "/Users/tomjrob/.virtualenvs/citex/lib/python2.7/site-packages/pybtex/database/input/bibtex.py", line 185, in parse_bibliography
    self.handle_error(error)
  File "/Users/tomjrob/.virtualenvs/citex/lib/python2.7/site-packages/pybtex/database/input/bibtex.py", line 358, in handle_error
    report_error(error)
  File "/Users/tomjrob/.virtualenvs/citex/lib/python2.7/site-packages/pybtex/errors.py", line 76, in report_error
    raise exception
pybtex.scanner.TokenRequired: entry key expected`

**Comment by michaelb1886** [comment]
pybtex parsing error. hmmmm. Try loading the .bib file in JabRef to see if Mandeley didn't mangle it.  'Entry key expected' would make me think that you have an article in your bibtex library without a key.

**Comment by tomjrob** [comment]
@michaelb1886, I don't know much about the bibtex format. What does it use as a key? Is it UUID or does it just use some kind of hash of author, year, title? I'll try loading up the library in JabRef as you suggest. I'll report back once I've investigated this further.

**Comment by tomjrob** [comment]
@michaelb1886, thanks for that. All fixed and working now - Mendeley does indeed export references that have missing bibtex keys. Perhaps some defensive code needs to be added to check for malformed .bib libraries.

The issue was arising in my library where author OR year was missing for a couple of book chapters. Mendely seems to create the bibtex key by concatenating `first author` with `year`.

**Comment by admiralakber** [comment]
The defensive code would have to be at the point of parsing the BibTeX file. We're currently relying on an external module to do the BibTeX file reading.

The easiest solution I can think of is writing our own lightweight parser.
